project:
  type: website
  output-dir: docs

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "alamap"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: rss
        href: index.xml
  page-footer:
    left: "Â© 2025 alamap.xyz"
    center: 
      - text: "Impressum"
        href: impressum.qmd
      - text: "Datenschutz"
        href: datenschutz.qmd
    right: "Always learn as much as possible"
    background: light # oder dark, passend zu Ihrem Design
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



